# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: "3.4"

services:
  ecommerce:
    image: ecommerce
    build:
      context: .
      dockerfile: src/ecommerce/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5241:5241
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
